# Generated by Django 4.2.1 on 2023-05-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_models1',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
